package com.company.taskManagmentSystem.comands.enums;

public enum CommandType {
    CREATEMEMBER,
    SHOWPEOPLE,
    SHOWPEOPLEACTIVITY,
    CREATETEAM,
    SHOWTEAM,
    SHOWTEAMACTIVITY,
    ADDPERSONTOTEAM,
    SHOWTEAMMEMBERS,
    CREATENEWBOARDTEAM,
    SHOWTEAMBOARD,
    CREATEBUGBOARD,
    CREATESTRORYBOARD,
    CREATEFEEDBACKBOARD,
    CHANGEPRIORITYBUG,
    CHANGESEVERITYBUG,
    CHANGESTATUSBUG,
    CHANGEPRIORITYSTORY,
    CHANGESIZESTORY,
    CHANGESTATUSSTORY,
    CHANGERATINGFEEDBACK,
    CHANGESTATUSFEEDBACK,
    ASSIGNETASKPERSON,
    UNASSIGNTASKPERSON,
    ADDCOMMENTTOTASK;

}
